language: ruby

rvm:
  - 2.4.6

services:
  - mysql
  - docker

cache:
  directories:
   - $PWD/public/lib/
   - $PWD/vendor/.bundle/

install:
  - cp config/database.yml.example config/database.yml
  - cp config/config.yml.example config/config.yml
  - cp db/schema.rb.example db/schema.rb
  - ./lib/exporter-deps.sh > /dev/null 2>&1
  - bundle check --path vendor/.bundle/ || bundle install --path vendor/.bundle/
  - yarn check || yarn install
  - mysql -e "CREATE DATABASE mapknitter_test; CREATE DATABASE mapknitter;"
  - if [ $RAILS_ENV == 'production' ]; then
      bundle exec rails db:schema:load;
    else
      bundle exec rails db:setup || bundle exec rails db:migrate;
    fi

env:
  global:
    - RAILS_ENV=test
    - CI=true
    - TRAVIS=true

# FIXME - Later change 'test/unit' and 'test/funcional' folders 
# to 'test/unit' and 'test/funcional', respectively

jobs:
  include:
    - name: "Unit Tests"
      script: bundle exec rails test:unit
    - name: "Integration Tests"
      script: bundle exec rails test:integration
    - name: "Functional Tests"
      script: bundle exec rails test:functional
    - name: "Rubocop Linter"
      script: bundle exec rubocop
    - name: "Docker Builds"
      script: docker build -t mapknitter .
    - name: "Asset Precompilation"
      env:
        - RAILS_ENV=production
      script:
        - bundle exec rails assets:precompile

branches:
  only:
    - main
    - unstable
    - development
